# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mghnv/drive/Documents/MtechProject/LSU_counter/LSU_counter.srcs/sources_1/ip/DMEM_1/DMEM.xci
# IP: The module: 'DMEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mghnv/drive/Documents/MtechProject/LSU_counter/LSU_counter.srcs/sources_1/ip/DMEM_1/DMEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMEM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/mghnv/drive/Documents/MtechProject/LSU_counter/LSU_counter.srcs/sources_1/ip/DMEM_1/DMEM.xci
# IP: The module: 'DMEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mghnv/drive/Documents/MtechProject/LSU_counter/LSU_counter.srcs/sources_1/ip/DMEM_1/DMEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMEM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
